name: Sync to GitLab

on:
  push:
    branches:
      - "**" # Sync all branches
  pull_request:
    branches:
      - main # Sync when a pull request is merged into the main branch
  create:
    branches:
      - "**" # Sync when a new branch is created
  delete:
    branches:
      - "**" # Sync when a branch is deleted

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history instead of a shallow clone

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/codewithamey/ResuMatch.git
          git push gitlab --all --force  # Push all branches
          git push gitlab --tags         # Push tags

      - name: Delete branches on GitLab (if deleted on GitHub)
        if: github.event_name == 'delete'
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/codewithamey/ResuMatch.git
          git push gitlab --delete ${{ github.event.ref }}  # Delete the branch on GitLab
